### ISSUE TITLE
how to access files within directory

### ISSUE THREAD

**Issue by ilearnbydoing** [juicyfx/now-builders#1]
Hi,

I am trying to access the .php files within folder and it gives 404 error though index.php works fine

is there any further step?
thanks

**Comment by f3l1x** [comment]
Hi. Can you show me the code and deployment?

**Comment by ilearnbydoing** [comment]
Hi composer working fine all the files at root folder is accessible but not the files within the subfolders I assume they are not being uploaded.
here is my now.json
{
    "version": 2,
    "builds": [
      {
        "src": "*.php",
        "use": "@juicyfx/php@canary",
        "config": {
          "composer": true
        }
      }
    ]
  }

**Comment by f3l1x** [comment]
Well, I need the whole project or minimal reproducible code.

**Comment by baboons** [comment]
Do you have something like a public folder that you want to use as entry? Then you should use something like this:

`  "builds": [
    {
      "src": "public/index.php",
      "use": "@juicyfx/php@canary",
      "config": {
        "mode": "server",
        "composer": true,
        "v": "7.3"
      }
    }
  ],
  "routes": [
    {
      "src": "/(.*) ",
      "dest": "/public/index.php"
    }`

**Comment by f3l1x** [comment]
Please take a look at new `now-php` builder (https://github.com/juicyfx/now-php).

**Comment by f3l1x** [comment]
Closing it here.
