### ISSUE TITLE
Mode CGI might have the wrong php settings for URI

### ISSUE THREAD

**Issue by baboons** [juicyfx/now-builders#2]
I played around with Symphony but got this issue with CGI `No route found for "GET /symfony-test.johantd04.now.sh/"`. It seems that the host is passed to the query string. Server works as expected.

I suspect that host would be removed `REQUEST_URI: host + path` for CGI launcher.js.

**Comment by f3l1x** [comment]
Could you please provide a minimal repo for it? Pure PHP would be better, but Symfony is also OK.

**Comment by baboons** [comment]
I will setup a repo later today, I haven't had the time yet for it. It should not be related to Symfony only.

**Comment by baboons** [comment]
I was preparing some simple tests but build fails due to gd and xsl is missing. Is that anything you would consider to add? if not I'll write a another test for it.

```
2019-08-01T20:15:56.928Z  PHP Warning:  PHP Startup: Unable to load dynamic library 'gd' (tried: /tmp/573d5347/node_modules/@juicyfx/php-lib-73/php/modules/gd (/tmp/573d5347/node_modules/@juicyfx/php-lib-73/php/modules/gd: cannot open shared object file: No such file or directory), /tmp/573d5347/node_modules/@juicyfx/php-lib-73/php/modules/gd.so (libX11.so.6: cannot open shared object file: No such file or directory)) in Unknown on line 0
2019-08-01T20:15:56.934Z  PHP Warning:  PHP Startup: Unable to load dynamic library 'xsl' (tried: /tmp/573d5347/node_modules/@juicyfx/php-lib-73/php/modules/xsl (/tmp/573d5347/node_modules/@juicyfx/php-lib-73/php/modules/xsl: cannot open shared object file: No such file or directory), /tmp/573d5347/node_modules/@juicyfx/php-lib-73/php/modules/xsl.so (libexslt.so.0: cannot open shared object file: No such file or directory)) in Unknown on line 0

```

and the libraries deps used that requires these extensions:

```
    "league/route": "^4.2",
    "zendframework/zend-diactoros": "^1.8",
    "league/container": "^3.2"
```

**Comment by f3l1x** [comment]
These extensions are supported on the Lambda, take a look. 

https://now-builders-php-ext-f3l1x.juicyfx1.now.sh/

But, and I don't know way, is calling composer during the build step triggers this warning.

**Comment by f3l1x** [comment]
> https://www.php.net/manual/en/reserved.variables.server.php
```
'REQUEST_URI'
The URI which was given in order to access this page; for instance, '/index.html'.
```

> https://aprelium.com/data/doc/2/abyssws-linux-doc-html/cgivars.html
```
SCRIPT_URL and REQUEST_URI: The original request URI sent by the client.
```

> http://www.cgi101.com/book/ch3/text.html
```
REQUEST_URI | The interpreted pathname of the requested document or CGI (relative to the document root)
```

**Comment by baboons** [comment]
> These extensions are supported on the Lambda, take a look.
> 
> https://now-builders-php-ext-f3l1x.juicyfx1.now.sh/
> 
> But, and I don't know way, is calling composer during the build step triggers this warning.

Yea, that is strange. I'll see if I can figure it out. I'll post an update here once I've confirmed it. Regards to REQUEST_URI it works as expected with FPM. CGI gets HOST + URI. Server does not work with custom suffixes, e.g. /api/users.json. Not sure if that that is a limitation with the dev server in php or not yet.

**Comment by f3l1x** [comment]
I have just bumped new version, can you please test it? REQUEST_URI should contains only URI.

**Comment by baboons** [comment]
> I have just bumped new version, can you please test it? REQUEST_URI should contains only URI.

Did't work. Something is still off with the CGI. Host is part of the req uri for some reason. `No route found for "GET /mumsit-api-fjwo6n5p4.now.sh/_profiler/open" (from "https://mumsit-api-fjwo6n5p4.now.sh/")`

**Comment by f3l1x** [comment]
I see, you're using `@juicyfx/php` not `now-php`. :-) Can you please test it once again? I've bumped also juicyfx/php.

**Comment by f3l1x** [comment]
Hi @baboons. Any progress? Did you have time for it? :-)

**Comment by f3l1x** [comment]
Please take a look at new `now-php` builder (https://github.com/juicyfx/now-php).

**Comment by f3l1x** [comment]
Closing it here.
