### ISSUE TITLE
Proposal: Config for composer install with-scripts 

### ISSUE THREAD

**Issue by baboons** [juicyfx/now-builders#3]
In some cases you'd have a post-install script in composer. It would be great to have the control in now.json whenever you would want to disable or enable scripts hooks for composer.

I suggest that `composer` would be departed and replaced with `composerJson` that refers to the file path, if the file exists it will build with composer. To support scripts `composerWithScripts` would be a bool to enable or disable this.

What do you think?

**Comment by f3l1x** [comment]
Hi. Let's put it on the roadmap, I like that.

I have separate PHP builder to the new repo, after discussion with ZEIT's members.

https://github.com/juicyfx/now-php

I focus on minimal setup with zero-config. Thus, only PHP 7.3 and server mode is support. But on the other hand, it has working `now dev` for local development. Local now dev is based on CGI mode. You've pointed some issue in #2.

**Comment by f3l1x** [comment]
Closing it here.
